version: 0.0
 
os: linux
files:
   - source: /HelloWorldMaven.war
     destination: /usr/local/apache-tomcat-7.0.54/webapps
permissions:
   - object: /usr/local/apache-tomcat-7.0.54/webapps
     pattern: "**"
     owner: tomcat
     group: tomcat
     mode: 755
     type:
       - file
hooks:
   AfterInstall:
   - location: /src/main/script/restarttomcat.sh
     runas: root